version: "3"
services:
  portal:
    build:
      dockerfile: Dockerfile
      context: .
    image: britors/angular-model-portal
    container_name: portal
    ports:
      - "80:80"
      - "443:443"
    networks:
      - portal-network
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "Secret@Portal!"
      MYSQL_DATABASE: "portal"
    container_name: portal_database
    ports:
      - "3306:3306"
    networks:
      - portal-network
  rabbit:
    image: rabbitmq:3-management
    container_name: portal_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - portal-network  
networks:
  portal-network:
    driver: bridge
